export interface CustomerType{
    customerId?:number, //Optional: when adding a customer an ID wont be available as that is generated by the database
    firstName:string,
    lastName:string,
    age:number,
    sex:CharacterData,
    email:string,
    dateAdded?:any
  }